### ISSUE TITLE
Ensure License is known for all packages

### ISSUE THREAD

**Issue by chrisdebian** [mocaccinoOS/issue-tracker#22]
Hi, 

I've just been searching for packages, and noticed that the package listing often omits the 'license-type/ name' in the 'License' field:

https://packages.mocaccino.org/

Would it be possible to include this information?

Thanks,

Chris

**Comment by mudler** [comment]
Hi!

Thank you for the feedback, some of the packages (that are coming from Gentoo, for example) don't have a License annotated because we are still actively working on the metadata conversion part.

This looks a dup of https://github.com/mocaccinoOS/issue-tracker/issues/1

**Comment by mudler** [comment]
Closing this in favor of #1 which is more detailed. Feel free to follow #1 for updates, thanks!

**Comment by chrisdebian** [comment]
Thank you.
