### ISSUE TITLE
GDM fails to start X

### ISSUE THREAD

**Issue by mudler** [mocaccinoOS/issue-tracker#26]
even after gdm in the video group, gdm fails to start X in portage-tree:

![VirtualBox_test_25_12_2020_12_18_31](https://user-images.githubusercontent.com/2420543/103143120-fb886180-4710-11eb-82ea-91472cd42b07.png)

See also: https://github.com/swaywm/sway/issues/1022#issuecomment-269593897

**Comment by geaaru** [comment]
It was related to `depmod -a` issue. Now GDM start correctly.
