### ISSUE TITLE
Add llvm10 libs on system-x layers or as single package

### ISSUE THREAD

**Issue by geaaru** [mocaccinoOS/issue-tracker#28]

**Comment by joostruis** [comment]
https://github.com/mocaccinoOS/portage-tree/blob/master/multi-arch/packages/layers/system-x/definition.yaml#L4

Think the whole clang layer could be added there.

**Comment by joostruis** [comment]
Seems that https://github.com/mocaccinoOS/portage-tree/blob/master/multi-arch/packages/layers/clang-9/build.yaml#L15

I'm confused.

**Comment by mudler** [comment]
No, this shouldn't go in system-x, but rather in gcc-base. https://github.com/mocaccinoOS/portage-tree/commit/d7d138e9eee2a189ed6723cb7ef495f01b20ca89
