### ISSUE TITLE
Review mocaccino kernel modules directory

### ISSUE THREAD

**Issue by geaaru** [mocaccinoOS/issue-tracker#31]
Atm the directory is `/lib/modules/5.4.84` instead of `/lib/modules/5.4-mocaccino`.

**Comment by mudler** [comment]
same is on mocaccino kernels (non-LTS)

**Comment by geaaru** [comment]
Done with https://github.com/mocaccinoOS/kernel-repo/pull/48

We use `MAJOR.MINOR.PATCH-mocaccino`
