### ISSUE TITLE
Gnome ISO: fix lock screen / black screen

### ISSUE THREAD

**Issue by geaaru** [mocaccinoOS/issue-tracker#35]
![image](https://user-images.githubusercontent.com/2205174/103234455-0117be80-4940-11eb-9bb9-8597814dd5dc.png)

Could be related to the missing user/group

**Comment by mudler** [comment]
Note: typo on fprintd service. Should point to /var/lib/fprint, not /var/lib/lib/fprint

**Comment by geaaru** [comment]
Gentoo issue probably. Temporary fixed:
https://github.com/mocaccinoOS/portage-tree/commit/50a1548ba9aac6f8b8954edb04e527ca5bc16b08#diff-821ffce7221a72f294c12e191c137745bce98933482c7ef7f1214b764e1a3885R14
