### ISSUE TITLE
Native kernel packages

### ISSUE THREAD

**Issue by mudler** [mocaccinoOS/issue-tracker#4]
We should have along also kernels built natively, instead of extracting them from entropy repositories

**Comment by geaaru** [comment]
Step1: For now I added the specs for build kernel from ebuild with emerge command: [kernel-5.8/sabayon-full](https://github.com/mocaccinoOS/kernel-repo/blob/master/packages/kernels/sabayon-full/5.8/build.yaml)

I think that we could try to compile also funtoo kernel with sabayon config.

**Comment by mudler** [comment]
Available here: https://github.com/mocaccinoOS/kernel-repo/tree/master/packages/kernels/mocaccino

I've also created the spin `MicroServer` with `k3s` and using our native kernels. Also `Micro` is not shipping k3s by default anymore.

Once proper QA, will move mocaccino kernels as defaults for our ISOs
