### ISSUE TITLE
Bump net-im/signal-desktop-bin to v1.39.5

### ISSUE THREAD

**Issue by Beep6581** [mocaccinoOS/issue-tracker#49]
Sabayon currently ships net-im/signal-desktop-bin-1.36.1 which is incompatible with the current version of Signal on Android/mac/Windows, so it is completely unusable.

Please bump to v1.39.5.

https://github.com/signalapp/Signal-Desktop/releases

**Comment by joostruis** [comment]
Will be in Entropy soon.
